apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:           # ‚Üê Remove namespace from here
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer