apiVersion: v1
kind: Service
metadata:
  name: cfrontend-app
  namespace: microservices
  labels:
    app: cfrontend-app      # ⬅️ CORRIGER le label
spec:
  type: NodePort
  selector:
    app: cfrontend-app      # ⬅️ CORRIGER pour matcher le déploiement
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30009