apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: microservices
  labels:
    app: frontend-app
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.2.88
  selector:
    app: frontend-app
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP