apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: microservices
  labels:
    app: frontend-app
spec:
  type: NodePort  # Change from LoadBalancer to NodePort
  selector:
    app: frontend-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 5000  # Fixed port 5000