apiVersion: v1
kind: Service
metadata:
  name: cfrontend-app
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: cfrontend-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30009